name: Run API Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-
    - name: Install Optic CLI
      run: npm install -g @useoptic/cli 
    - name: Install app dependencies
      run: npm ci
    - name: Run API tests
      run: api run test --ci --exit-on-diff
    - name: Generate an OpenAPI file
      run: yarn generateOas && cat .optic/generated/openapi.yaml
