name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: egordm/gha-yarn-node-cache@v1
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15
    - name: Install dependencies
      run: |
        yarn global add @useoptic/cli &&
        yarn install --frozen-lockfile &&
        echo "$(yarn global bin)" >> $GITHUB_PATH
    - name: Run API tests
      run: api run test --ci --exit-on-diff
    - name: Generate an OpenAPI file
      run: yarn generateOas && cat .optic/generated/openapi.yaml
    - name: Optic Changelog
      uses: opticdev/optic-changelog@main
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        OPTIC_API_KEY: ${{secrets.OPTIC_API_KEY}}
    - name: API Checks
      run: node checks.js
      env:
        SPECTACLE_URL: "http://localhost:34444/api/specs/1/spectacle"
