name: Optic Share

on:
  pull_request:
    branches: [main]

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Optic CLI
      run: npm install --global --legacy-peer-deps @useoptic/cli
    - name: Generate OpenAPI
      run: api generate:oas --baseDocument=./base-openapi.yml
    - name: Share OpenAPI
      # At this point, we could push the OpenAPI file somewhere
      run: cat .optic/generated/openapi.yaml