name: Optic Changelog

on:
  pull_request:
    branches: [main]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Optic Changelog
      uses: opticdev/optic-changelog@main
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        OPTIC_API_KEY: ${{secrets.OPTIC_API_KEY}}
